name: oe_accept
description: Isolated dummy client for accept/reject assigned delivery actions.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
